codeforlife/kurono/avatar_state.py
codeforlife/kurono/backpack.py
codeforlife/kurono/pathfinding.py
codeforlife/kurono/utils.py
codeforlife/kurono/world_map.py
codeforlife/mixins/__init__.py
codeforlife/mixins/cron_mixin.py
codeforlife/permissions/__init__.py
codeforlife/permissions/is_cron_request_from_google.py
codeforlife/user/admin.py
codeforlife/user/models/classroom.py
codeforlife/user/models/other.py
codeforlife/user/models/school.py
codeforlife/user/models/session.py
codeforlife/user/models/student.py
codeforlife/user/models/teacher.py
codeforlife/user/models/teacher_invitation.py
codeforlife/user/models/user.py
manage.py
pyproject.toml
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/11)

feat: google cron mixin

---

codeforlife/py.typed

This fix add the types marker file for PEP 561. This informs static type checkers like mypy that the codeforlife package supports type hints. We are using inline type hints there's no need to specify anything in the marker file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/23)

fix: add types marker file

---

Pipfile
Pipfile.lock
codeforlife/email.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/56)

feat: email helpers

---

.github/workflows/main.yml
.vscode/settings.json
Pipfile
Pipfile.lock
codeforlife/models/__init__.py
codeforlife/permissions/__init__.py
codeforlife/tests/__init__.py
codeforlife/tests/permission.py
codeforlife/types.py
codeforlife/user/fixtures/schools.json
codeforlife/user/fixtures/teachers.json
codeforlife/user/fixtures/users.json
codeforlife/user/models/klass.py
codeforlife/user/tests/permissions/test_in_class.py
codeforlife/user/tests/permissions/test_in_school.py
codeforlife/user/tests/permissions/test_is_independent.py
codeforlife/user/tests/permissions/test_is_student.py
codeforlife/user/tests/permissions/test_is_teacher.py
pyproject.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/57)

fix: view permissions unit tests

---

.vscode/workspace.code-snippets
codeforlife/permissions/__init__.py
codeforlife/permissions/allow_none.py
codeforlife/permissions/is_cron_request_from_google.py
codeforlife/serializers/base.py
codeforlife/tests/model_view_set.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/61)

fix: new permissions and fix test cases

---

codeforlife/tests/__init__.py
codeforlife/tests/model_serializer.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/66)

feat: ModelSerializerTestCase

---

codeforlife/tests/model_serializer.py
codeforlife/tests/model_view_set.py
codeforlife/types.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/67)

fix: add assertions

---

codeforlife/serializers/base.py
codeforlife/serializers/model.py
codeforlife/user/auth/backends/__init__.py
codeforlife/user/auth/backends/email_and_password.py
codeforlife/user/auth/backends/otp.py
codeforlife/user/auth/backends/otp_bypass_token.py
codeforlife/user/auth/backends/user_id_and_login_id.py
codeforlife/user/auth/backends/username_and_password_and_class_id.py

- added view property base serializers
- fixed various type hints
- fixed various lint errors
- email case insensitive search in auth backend
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/68)

fix: view property, type hints, linting, email case insensitive search

---

codeforlife/tests/model_view_set.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/75)

fix: print json error

---

.devcontainer.json
codeforlife/models/base.py
codeforlife/settings/django.py
codeforlife/urls.py
codeforlife/user/models/otp_bypass_token.py
codeforlife/user/models/student.py
codeforlife/user/models/teacher.py
codeforlife/user/models/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/119)

fix: convert to backend repo

---

codeforlife/settings/django.py
codeforlife/tests/model_view_set.py
codeforlife/urls.py
manage.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/123)

feat: backend template

---

codeforlife/middlewares/__init__.py
codeforlife/middlewares/session.py
codeforlife/settings/custom.py
codeforlife/settings/django.py
manage.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/126)

fix: delete session metadata cookie

---

codeforlife/filters.py
codeforlife/tests/model_view_set.py
codeforlife/user/filters/__init__.py
codeforlife/user/filters/klass.py
codeforlife/user/filters/user.py
codeforlife/user/models/teacher.py
codeforlife/user/views/klass.py
codeforlife/user/views/klass_test.py
codeforlife/user/views/user_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/127)

fix: Portal frontend19

---

codeforlife/user/filters/user.py
codeforlife/user/models/user.py
codeforlife/user/serializers/user.py
codeforlife/user/serializers/user_test.py
codeforlife/user/views/user.py
codeforlife/user/views/user_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/131)

fix: portal frontend 45

---

codeforlife/user/models/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/132)

fix: Portal frontend 50

---

codeforlife/tests/api.py
codeforlife/urls.py
codeforlife/urls/__init__.py
codeforlife/urls/handlers.py
codeforlife/urls/patterns.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/133)

fix: Contributor frontend 4

---

.github/workflows/main.yml
Pipfile
Pipfile.lock
codeforlife/models/signals/__init__.py
codeforlife/settings/__init__.py
codeforlife/settings/custom.py
codeforlife/settings/django.py
codeforlife/settings/third_party.py
codeforlife/tests/api.py
codeforlife/tests/model_serializer.py
codeforlife/tests/model_view_set.py
codeforlife/user/auth/password_validators/independent_test.py
codeforlife/user/auth/password_validators/student_test.py
codeforlife/user/auth/password_validators/teacher_test.py
codeforlife/user/models/__init__.py
codeforlife/user/models/teacher.py
codeforlife/user/models/user.py
codeforlife/user/serializers/user.py
codeforlife/user/serializers/user_test.py
codeforlife/user/views/school_test.py
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/134)

fix: Upgrade to Python 3.12

---

codeforlife/user/filters/klass.py
codeforlife/user/models/teacher.py
codeforlife/user/views/klass.py
codeforlife/user/views/klass_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/136)

fix: Portal frontend 52

---

codeforlife/user/models/user.py
codeforlife/user/views/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/141)

fix: user queryset

---

codeforlife/user/permissions/is_independent.py
codeforlife/user/views/school.py
codeforlife/user/views/school_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/147)

fix: Allow requester indies to retrieve school

---

codeforlife/user/signals/__init__.py
codeforlife/user/signals/auth_factor.py
codeforlife/user/signals/auth_factor_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/150)

fix: portal backend 376
