ocadotechnology/codeforlife-package-python

- .github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/13)
> fix: set git profile

- codeforlife/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/15)
> fix: service name not found pattern

- codeforlife/request.py
- codeforlife/settings/django.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/16)
> fix: session cookie and drf request

- .github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/26)
> ci: Replace Stefbot with CFLbot

- .github/workflows/contributing.yaml
- README.md
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/52)
> Validate existing contributor

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/59)
> Add .venv folder

- codeforlife/serializers/__init__.py
- codeforlife/serializers/base.py
- codeforlife/serializers/model.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/models/otp_bypass_token.py
- codeforlife/user/models/user.py
- codeforlife/user/serializers/klass.py
- codeforlife/user/serializers/school.py
- codeforlife/user/serializers/student.py
- codeforlife/user/serializers/teacher.py
- codeforlife/user/serializers/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/65)
> fix: various fixes for bulk logic and type hints

- codeforlife/permissions/__init__.py
- codeforlife/permissions/allow_none.py
- codeforlife/permissions/is_cron_request_from_google.py
- codeforlife/permissions/operators.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/permissions/in_class.py
- codeforlife/user/permissions/in_school.py
- codeforlife/user/permissions/is_independent.py
- codeforlife/user/permissions/is_student.py
- codeforlife/user/permissions/is_teacher.py
- codeforlife/user/tests/views/test_klass.py
- codeforlife/user/tests/views/test_school.py
- codeforlife/user/tests/views/test_user.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/69)
> fix: assertion helpers

- codeforlife/serializers/base.py
- codeforlife/tests/model_serializer.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/models/user.py
- codeforlife/user/tests/auth/password_validators/base.py
- codeforlife/user/tests/views/test_klass.py
- codeforlife/user/tests/views/test_school.py
- codeforlife/user/views/klass.py
- codeforlife/user/views/school.py
- codeforlife/user/views/user.py
- codeforlife/views/api.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/73)
> fix: create class

- codeforlife/serializers/model.py
- codeforlife/tests/model_serializer.py
- codeforlife/tests/model_view_set.py
- codeforlife/types.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/76)
> fix: create class 2

- Pipfile
- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/77)
> fix: Upgrade Django and other packages

- codeforlife/serializers/base.py
- codeforlife/views/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/79)
> fix: missing user props

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/80)
> fix: support dev extra

- Pipfile.lock
- codeforlife/tests/model_serializer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/82)
> fix: Copy validated data dicts

- codeforlife/tests/model_view_set.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/83)
> fix: Pop kwargs or None

- codeforlife/request.py
- codeforlife/serializers/base.py
- codeforlife/user/models/user.py
- codeforlife/user/views/klass.py
- codeforlife/user/views/school.py
- codeforlife/user/views/user.py
- codeforlife/views/__init__.py
- codeforlife/views/api.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/90)
> fix: anonymize user

- codeforlife/request.py
- codeforlife/serializers/model.py
- codeforlife/tests/__init__.py
- codeforlife/tests/api.py
- codeforlife/tests/model_serializer.py
- codeforlife/tests/model_view_set.py
- codeforlife/types.py
- codeforlife/user/models/__init__.py
- codeforlife/user/models/teacher.py
- codeforlife/user/models/user.py
- codeforlife/user/serializers/__init__.py
- codeforlife/user/serializers/teacher.py
- codeforlife/user/serializers/user.py
- codeforlife/user/views/user.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/93)
> feat: release students

- codeforlife/user/fixtures/independent.json
- codeforlife/user/fixtures/school_1.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/99)
> fix: Update class fixtures for class join requests

- codeforlife/user/management/commands/summarize_fixtures.py
- codeforlife/user/serializers/klass.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/95)
> fix: transfer class

- codeforlife/response.py
- codeforlife/serializers/model.py
- codeforlife/tests/__init__.py
- codeforlife/tests/model_serializer.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/models/teacher.py
- codeforlife/user/models/user.py
- codeforlife/user/serializers/__init__.py
- codeforlife/user/serializers/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/101)
> fix: fix data structure and test helpers

- codeforlife/permissions/__init__.py
- codeforlife/permissions/allow_any.py
- codeforlife/tests/model_serializer.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/models/user.py
- codeforlife/views/__init__.py
- codeforlife/views/decorators.py
- codeforlife/views/model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/103)
> fix: update password

- codeforlife/user/fixtures/school_3.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/105)
> fix: school_3 fixture

- Pipfile
- Pipfile.lock
- codeforlife/user/auth/password_validators/independent.py
- codeforlife/user/auth/password_validators/student.py
- codeforlife/user/auth/password_validators/teacher.py
- codeforlife/user/models/__init__.py
- codeforlife/user/models/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106)
> feat: Create indy user

- codeforlife/settings/django.py
- codeforlife/tests/model_view_set.py
- codeforlife/user/fixtures/non_school_teacher.json
- codeforlife/user/models/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/116)
> fix: school teacher invitation

- codeforlife/mail.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/122)
> fix: dd contact endpoint

- Pipfile
- Pipfile.lock
- codeforlife/settings/django.py
- codeforlife/user/models/user.py
- manage.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/130)
> fix: Remove Kurono

- Pipfile
- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/139)
> fix: use new version of portal

- codeforlife/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/140)
> fix: trigger deployment

- codeforlife/user/fixtures/sites.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/142)
> fix: sites

- codeforlife/commands/__init__.py
- codeforlife/commands/load_fixtures.py
- codeforlife/commands/summarize_fixtures.py
- codeforlife/settings/custom.py
- codeforlife/urls/patterns.py
- codeforlife/user/management/commands/load_fixtures.py
- codeforlife/user/management/commands/summarize_fixtures.py
- codeforlife/views/__init__.py
- codeforlife/views/health_check.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/146)
> feat: Contributor backend 31

- Pipfile
- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/153)
> fix: django v4.2.20

- .github/workflows/main.yml
- Pipfile
- Pipfile.lock
- codeforlife/settings/otp.py
- codeforlife/settings/third_party.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/156)
> fix: aws sqs

- codeforlife/servers/base.py
- codeforlife/servers/celery.py
- codeforlife/servers/django.py
- codeforlife/settings/django.py
- codeforlife/settings/third_party.py
- codeforlife/tasks.py
- codeforlife/tests/celery.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/157)
> feat: Workspace 220

- Pipfile
- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/165)
> fix: Install latest common and RR

- codeforlife/request/drf.py
- codeforlife/tests/api_client.py
- codeforlife/user/auth/backends/google.py
- codeforlife/user/fixtures/google_users.json
- codeforlife/user/models/user/__init__.py
- codeforlife/user/models/user/google.py
- codeforlife/user/models/user/user.py
- codeforlife/user/permissions/__init__.py
- codeforlife/user/permissions/is_independent.py
- codeforlife/user/permissions/is_teacher.py
- codeforlife/user/permissions/synced_with_google.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/167)
> fix: Portal backend 404
